name: Publish

on: 
  push:
    branches:
      - "!master"

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    name: Build Library
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd'
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master
          ./build.cmd
