name: Publish

on:
  push:
    branches:
      - master

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run './build.cmd'
        run: ./build.cmd
