name: Publish

on:
  push:
    branches:
      - master

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd'
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master
          ./build.cmd
